
import { Product } from '@/types/product';
import { CartItem } from '@/types/cart';

// Mock product data
const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Fit Cotton T-Shirt',
    brand: 'Essentials',
    description: 'A comfortable cotton t-shirt with a classic fit, perfect for everyday wear.',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'apparel',
    rating: 4.5,
    reviewCount: 128,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Navy'],
    inStock: true,
  },
  {
    id: '2',
    name: 'Premium Running Shoes',
    brand: 'Sportix',
    description: 'Lightweight and responsive running shoes designed for maximum performance and comfort.',
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'footwear',
    rating: 4.8,
    reviewCount: 94,
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black/Red', 'Blue/White', 'Gray/Yellow'],
    inStock: true,
  },
  {
    id: '3',
    name: 'Leather Minimalist Watch',
    brand: 'Chronos',
    description: 'A sleek minimalist watch with genuine leather strap and Japanese quartz movement.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'accessories',
    rating: 4.3,
    reviewCount: 67,
    sizes: ['One Size'],
    colors: ['Brown/Gold', 'Black/Silver'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Slim Fit Denim Jeans',
    brand: 'Denim Co.',
    description: 'Classic slim fit jeans made from premium stretch denim for style and comfort.',
    price: 49.99,
    originalPrice: 69.99,
    discount: 28,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'apparel',
    rating: 4.6,
    reviewCount: 215,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Blue', 'Black', 'Gray'],
    inStock: true,
  },
  {
    id: '5',
    name: 'Wireless Bluetooth Headphones',
    brand: 'SoundWave',
    description: 'Premium wireless headphones with active noise cancellation and 30-hour battery life.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'accessories',
    rating: 4.7,
    reviewCount: 183,
    sizes: ['One Size'],
    colors: ['Black', 'White', 'Rose Gold'],
    inStock: true,
  },
  {
    id: '6',
    name: 'Classic Polo Shirt',
    brand: 'Urban Style',
    description: 'A timeless polo shirt made from soft cotton pique fabric with a clean, modern fit.',
    price: 34.99,
    originalPrice: 44.99,
    discount: 22,
    image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'apparel',
    rating: 4.4,
    reviewCount: 97,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Red', 'Black'],
    inStock: true,
  },
  {
    id: '7',
    name: 'Canvas Tote Bag',
    brand: 'EcoLife',
    description: 'Durable canvas tote bag with ample space, perfect for daily use and grocery shopping.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1601379327928-bedfaf9da2d0?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'accessories',
    rating: 4.2,
    reviewCount: 56,
    sizes: ['One Size'],
    colors: ['Natural', 'Black', 'Navy'],
    inStock: true,
  },
  {
    id: '8',
    name: 'Suede Chelsea Boots',
    brand: 'FootLuxe',
    description: 'Stylish suede Chelsea boots with elastic side panels and a comfortable low heel.',
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'footwear',
    rating: 4.6,
    reviewCount: 84,
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Tan', 'Black', 'Brown'],
    inStock: true,
  },
  {
    id: '9',
    name: 'Structured Backpack',
    brand: 'TrekGear',
    description: 'Modern, durable backpack with multiple compartments and laptop sleeve.',
    price: 59.99,
    originalPrice: 74.99,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'accessories',
    rating: 4.8,
    reviewCount: 112,
    sizes: ['One Size'],
    colors: ['Black', 'Gray', 'Navy'],
    inStock: true,
  },
  {
    id: '10',
    name: 'Casual Oxford Shirt',
    brand: 'Essentials',
    description: 'Crisp cotton oxford shirt with a button-down collar, perfect for casual or smart casual looks.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'apparel',
    rating: 4.5,
    reviewCount: 76,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Blue', 'Pink'],
    inStock: true,
  },
  {
    id: '11',
    name: 'Athletic Sneakers',
    brand: 'Sportix',
    description: 'Versatile athletic sneakers suitable for workouts, running, and casual wear.',
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'footwear',
    rating: 4.7,
    reviewCount: 135,
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['White/Blue', 'Black/Red', 'Gray/Green'],
    inStock: true,
  },
  {
    id: '12',
    name: 'Aviator Sunglasses',
    brand: 'VisionStyle',
    description: 'Classic aviator sunglasses with polarized lenses and UV protection.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    category: 'accessories',
    rating: 4.4,
    reviewCount: 68,
    sizes: ['One Size'],
    colors: ['Gold/Green', 'Silver/Blue', 'Black/Black'],
    inStock: true,
  },
];

// Mock cart data
const mockCartItems: CartItem[] = [
  {
    id: '1',
    name: 'Classic Fit Cotton T-Shirt',
    brand: 'Essentials',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    size: 'M',
    color: 'Black',
    quantity: 1,
  },
  {
    id: '8',
    name: 'Suede Chelsea Boots',
    brand: 'FootLuxe',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    size: '9',
    color: 'Brown',
    quantity: 1,
  },
];

// Get a random subset of products
export const getMockProducts = (count: number = 10): Product[] => {
  const shuffled = [...mockProducts].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

// Get product by ID
export const getMockProductById = (id: string): Product | null => {
  return mockProducts.find(product => product.id === id) || null;
};

// Get cart items
export const getMockCartItems = (): CartItem[] => {
  return mockCartItems;
};
